### PR TITLE
Proposals/version 2.0

### PR DESCRIPTION
**Pull request by cdevroe**
We are getting closer and closer to having Version 2.0 done. It includes some nice updates like a more traditional tagging UI, easy to edit mark titles, and several other enhancements.

It is a slow process as we have only a very limited amount of time to spend on Unmark these days. Thanks for your patience. We're eager to get this release out soon. We use Unmark daily too!

### CODE REVIEW

**Comment by khromov** [comment]
Is there a list of tasks that need to be fixed before 2.0 release that a volunteer could help with? 😄

**Comment by cdevroe** [comment]
@khromov That is very nice of you to ask. Thank you.

We have a few more updates staged for this release. Very small things to address, mostly related to layouts on different devices.

Perhaps you'd like to cherry pick an Issue or two for an upcoming release? Have a look through the issues to see if anything stands out to you that you'd like to help tackle.

**Comment by immanuelfodor** [comment]
I've just found Unmark, but wow, that GIF on the main page is really impressive, I'm really waiting for the v2 :)

**Comment by cdevroe** [comment]
Attn all: This will likely be merged in relatively soon. We will be changing the versioning from a X.x type system to a YYYY.x type system. So, rather than this officially being version 2.0 it will end up being 2020.1

Side note: This version has been running on [Unmark's hosted version](https://unmark.it/) for months and we've only had a very few issues which have all been addressed and released into this build.

**Pull request merged**
