### PR TITLE
Fix `window.opener` vulnerability

### PR DESCRIPTION
**Pull request by walialu**
Previously, unmark.it allowed any site
to modify the location of the referring browser window,
allowing their site to navigate you to a new page of their choosing.

See: https://dev.to/phishing
for more info.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@cdevroe I think this should not cause any issues, and could be a real vulnerability... so better merge it

**Comment by cdevroe** [comment]
I do not believe this to be a vulnerability nor do I believe it is exclusive to Unmark. Thanks for contributing code @walialu ... since this is now hosted on your own platform you should be able to control this code on your own if you think it is needed.

**Comment by walialu** [comment]
I don't like being the nagging fucktard, but in fact it's a longstanding issue/vuln.

See: https://developers.google.com/web/tools/lighthouse/audits/noopener

Yes, you are correct. There are in fact hundreds of thousands of affected websites.
But that doesn't mean, it's not an issue.

I already patched it at my local instance.

**Comment by cdevroe** [comment]
@walialu Is this exclusive to Chrome? Why in the world would they build web browsers this way? I take back my statement re: this not being a vulnerability. We _will_ roll this into 1.8

**Comment by cdevroe** [comment]
@walialu Since there are numerous conflicts (not your fault) I'll simply look at your commit and implement these changes manually.

**Comment by walialu** [comment]
Thanks a lot, Colin!

**Comment by walialu** [comment]
Fix implemented in https://github.com/cdevroe/unmark/commit/ba5f9f8f133a691447945f6323391887068dee34

**Pull request closed without merging**
